---
- name: Check if the playbook is being executed on supported os
  ansible.builtin.fail:
    msg: "This playbook is designed to work on ubuntu and redhat only"
  when: ansible_facts['distribution'] != "Ubuntu" and ansible_facts['distribution'] != "CentOS"

- name: Include OS-specific variables.
  include_vars: "{{ ansible_facts['distribution'] }}.yml"

- name: Install apache
  ansible.builtin.package:
    name: "{{ package_name}}"
    update_cache: yes   
    state: present
  notify: Apache is installed

- name: Enable apache
  ansible.builtin.systemd:
    name: "{{ package_name}}"
    enabled: true
    state: started
  notify: Apache is enabled 

- name: Install php packages
  ansible.builtin.package:
    name: "{{ item }}"          
    update_cache: yes
    state: present
    loop: "{{ php_packages }}"
  notify: 
    - restart apache
    - install php packages

- name: Copy info.php
  ansible.builtin.copy:
    src: info.php
    dest: "{{ info_page }}"
  notify: 
    - restart apache
    - info php

